# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Dahoon Bok
baseurl:        ""
url:            "http://bokdahoon.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Dahoon Bok
  url:          http://bokdahoon.github.io/
  email:        potter7050@naver.com
  github:       BokDaHoon
  twitter:      potter7050

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/BokDaHoon/bokdahoon.github.io